### PR TITLE
requirements.txt updated

### PR DESCRIPTION
**Pull request by nlok5923**
fixes: #142

### CODE REVIEW

**Comment by nlok5923** [comment]
@iiitv/project-maintainers sir please review this pull request.

**Comment by mohitkyadav** [comment]
@nlok5923 have you tested all the functionality?

**Comment by nlok5923** [comment]
@mohitkyadav no sir i hadn't tested all functionality i just use pip freeze command to get/update information about all the package installed in the project. sir i think for testing functionality a seperate issue will be good.

**Comment by nlok5923** [comment]
> @mohitkyadav sir i hadn't tested all functionality i just use pip freeze command to get/update information about all the package installed in the project. sir i think for testing functionality a seperate issue will be good.

**Comment by aashutoshrathi** [comment]
@nlok5923 The issue never said update dependencies and break the project. 🙂
Please make sure things work after you updated them.
PS: I think some of them need to be downgraded again to keep the project working.

cc: @mohitkyadav @iiitv/project-maintainers

**Comment by nlok5923** [comment]
> @nlok5923 The issue never said update dependencies and break the project. 🙂
> Please make sure things work after you updated them.
> PS: I think some of them need to be downgraded again to keep the project working.
> 
> cc: @mohitkyadav @iiitv/project-maintainers

@aashutoshrathi sir please can you help me how can i do this as i am new to django.

**Comment by mohitkyadav** [comment]
@nlok5923 follow the instructions in the readme. Ask questions in slack if need help.

**Review by yashshah2820 — CHANGES_REQUESTED** [review]
are all these packages required for the project?

**Comment by aashutoshrathi** [comment]
Doesn't look like that, one needs to check it.

**Pull request closed without merging**
