### PR TITLE
Create general project structure

### PR DESCRIPTION
**Pull request by singhpratyush**
Upon merging this PR, the project structure will become generic and easy to deploy on most cloud platforms.

Please [browse the branch](https://github.com/iiitv/Odyssy/tree/general) to know understand the structure better.

### CODE REVIEW

**Comment by aviaryan** [comment]
@singhpratyush Any reason why you deleted the .openshift files ? 
Other changes look good.

**Comment by singhpratyush** [comment]
@aviaryan: Photocatalogue requires a dependency that needs to be installed as root, and that is not possible on `Openshift`. So I was moving the deployment to `AWS`.

**Comment by yashLadha** [comment]
There are conflicts in this PR. Can you Please resolve them? Other thing looks good.

**Comment by singhpratyush** [comment]
I think I need time before I actually bring this in a state to merge. There are many things to think about for this and I hardly find any time. Will update it later.

**Comment by yashLadha** [comment]
Closing as stale PR feel free to reopen.

**Pull request closed without merging**
