### PR TITLE
Added UI to Events, News, Announcements

### PR DESCRIPTION
**Pull request by geekyJock8**
Also referenced the issue #68.
Also improved some font styling.
Here are some Screenshots: 
image

image

image

### CODE REVIEW

**Comment by Monal5031** [comment]
@geekyJock8 sir please deploy, as deployment would enable us to find bugs more easily.

**Comment by geekyJock8** [comment]
@Monal5031 Unable to make an account, so can't deploy. Make a local branch and try testing locally. Sorry for the inconvenience 😞 .

**Comment by mohitkyadav** [comment]
Space between photos of different widths seems inconsistent.
screenshot 119

screenshot 120

**Comment by geekyJock8** [comment]
@mohitkyadav I have added variable width to the carousel, inconsistent width problem should be solved now.

**Comment by Monal5031** [comment]
@Prakash2403 @yashLadha Please review this one.

**Pull request merged**
