### PR TITLE
Added Academic app

### LINKED ISSUE #78: Create app for Academics
This app would be used to display items under nav-bar item `Academics`

### Features:
Following views are to be added at `academics/view-name/`:
* B.tech (`academics/btech/course/`)
    * CSE
    * IT
* M.Tech (`academics/mtech/course/`)
    * CSE
    * IT
* Ph.D
* Academic Calendar

### PR DESCRIPTION
**Pull request by Monal5031**
Closes #78
deployed:  http://13.126.164.61:8000/
username : test
password: test

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
Deploy Please

**Comment by Monal5031** [comment]
@aashutoshrathi done, please review.

**Comment by yashLadha** [comment]
There are conflicts with `settings.py`. Resolve them.

**Comment by Monal5031** [comment]
Done @yashLadha sir.

**Pull request merged**
