### PR TITLE
Added Tags app

### LINKED ISSUE #15: Create app for tags
The app would be used to create tags for pictures and news.

### Features
* Verification for validity - should be `^[a-zA-Z0-9][a-zA-Z0-9\-]{3,}$`
* Views
  * `/tag/<tag>/`
  * `/tag/<tag>/pictures`
  * `/tag/<tag>/news`
  * `/tag/<tag>/announcement`

### PR DESCRIPTION
**Pull request by yashLadha**
Close #15

### CODE REVIEW

**Comment by yashLadha** [comment]
@singhpratyush can u help me with this duplicate code issue.

**Comment by singhpratyush** [comment]
You  may introduce the following function to handle paginations - 
```python
def paginate(queryset, page_no, no_items):
   ...
```

**Comment by yashLadha** [comment]
Sir still no good. @singhpratyush

**Comment by singhpratyush** [comment]
That much duplication is fine. We can do with that.

**Comment by yashLadha** [comment]
I am going to integrate Taggit with the modules. So now this PR is of no relevance to the Project . Closing this.

**Pull request closed without merging**
